options:
    # Install and upgrade charm related options
    extra_packages:
        type: string
        default: ""
        description: >
                Extra packages to install. A space delimited list of packages.
    package_status:
        default: "install"
        type: string
        description: >
            The status of service-affecting packages will be set to this
            value in the dpkg database. Useful valid values are "install"
            and "hold".
    install_sources:
        type: string
        description: >
            charm-helpers standard listing of package install sources.
            If you are using Datastax Enterprise, you will need to
            override one defaults with your own username and password.
        default: |
            - ppa:webupd8team/java
            - deb http://www.apache.org/dist/cassandra/debian 21x main
        #   - deb http://debian.datastax.com/community stable main
        #   DSE requires you to register and add your username/password here.
        #   - deb http://un:pw@debian.datastax.com/enterprise stable main
    install_keys:
        type: string
        description: >
            charm-helpers standard listing of package install source
            signing keys, corresponding to install_sources.
        default: |
            - null  # PPA keys securly added via Launchpad.
            - null  # Apache package signing key added automatically.
            # - null  # DataStack package signing key added automatically.
    edition:
        type: string
        default: community
        description: >
            One of 'community' or 'dse'. 'community' uses the
            Apache Cassandra packages. 'dse' is for DataStax
            Enterprise. Selecting 'dse' overrides the jvm setting
            constitutes acceptance of the Oracle Java Standard
            Edition license per
            http://www.oracle.com/technetwork/java/javase/terms/license/.
            The Community edition is recommended for use with this charm.
    jvm:
        type: string
        default: openjdk
        description: >
            Which Java runtime environment to use. May be 'openjdk' or
            'oracle'. Choosing 'oracle' constitutes acceptance of the
            Oracle Java Standard Edition license per
            http://www.oracle.com/technetwork/java/javase/terms/license/.
    # Storage configuration
    wait_for_storage_broker:
        type: boolean
        default: False
        description: >
            Do not start the service before external storage has been
            mounted using the block storage broker relation. If you do
            not set this and you relate the service to the storage
            broker, then your service will have started up using local
            disk, and later torn down and rebuilt when the external
            storage became available.
    data_file_directories:
         type: string
         default: data
         description: >
            Space delimited data directories. Use multiple data
            directories to split data over multiple physical hardware
            drive partitions. Paths are relative to /var/lib/cassandra
            or the block storage broker external mount point.
    commitlog_directory:
         type: string
         default: commitlog
         description: >
             Commit log directory. The path is relative to
             /var/lib/cassandra or the block storage broker external
             mount point.
    saved_caches_directory:
         type: string
         default: saved_caches
         description: >
             Saved caches directory. The path is relative to
             /var/lib/cassandra or the block storage broker external
             mount point.
    io_scheduler:
        type: string
        default: "noop"
        description: >
            Set kernel io scheduler for persistent storage.
            https://www.kernel.org/doc/Documentation/block/switching-sched.txt
 
    # private_dse_url:
    #     type: string
    #     default: ""
    #     description: >
    #         URL for the private dse tar file. Tar file of all the dse deb packages.
    #         Used when external apt repositories are not allowed or available.
    #
    #
##     units-to-update:
##         type: string
##         default: "all"
##         description: >
##             Comma separated list of unit numbers to update (i.e. modify
##             /etc setup and trigger cassandra restart on config-change or
##             upgrade-charm), or "all".
##             https://www.kernel.org/doc/Documentation/block/switching-sched.txt

    # nrpe-external-master relation related options
    nagios_context:
      default: "juju"
      type: string
      description: |
        Used by the nrpe subordinate charms.
        A string that will be prepended to instance name to set the host name
        in nagios. So for instance the hostname would be something like:
            juju-myservice-0
        If you're running multiple environments with the same services in them
        this allows you to differentiate between them.
    nagios_servicegroups:
      default: ""
      type: string
      description: >
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup
    nagios_heapchk_warn_pct:
        default: 80
        type: int
        description: >
            The pct of heap used to trigger a nagios warning
    nagios_heapchk_crit_pct:
        default: 90
        type: int
        description: >
            The pct of heap used to trigger a nagios critcal alert
    nagios_disk_warn_pct:
        default: 50 
        type: int
        description: >
            The pct of data disk used to trigger a nagios warning
    nagios_disk_crit_pct:
        default: 25 
        type: int
        description: >
            The pct of data disk used to trigger a nagios critcal alert

    # cassandra-env.sh related options
    max_heap_size:
        type: string
        default: ''
        description: >
            Total size of Java memory heap, for example 1G or 512M.
            If you set this, you should also set heap_newsize.
    heap_newsize:
        type: string
        default: ''
        description: >
            The size of the JVM's young generation in the heap. If you
            set this, you should also set max_heap_size. If in doubt,
            go with 100M per physical CPU core. Default is automatically
            tuned.

##     new-gen-size:
##         type: string
##         default: 100M
##         description: >
##             Size of Java new generation memory, for example 100M.  Only used
##             if auto-memory = false.
##     extra-jvm-opts:
##         type: string
##         default: ""
##         description: |
##             string to be appended to JVM_OPTS, e.g.:
##             -javaagent:$CASSANDRA_HOME/lib/jamm-0.2.5.jar


##     # cassandra-rackdc.properties for GossipingPropertyFileSnitch related
##     # options
##     prefer_local:
##         default: False
##         type: boolean
##         description:
##             Used with endpoint_snitch=GossipingPropertyFileSnitch to
##             prefer the internal ip when possible, as the
##             Ec2MultiRegionSnitch does. Used with cassandra >= 1.2.x
##     dc_suffix:
##         type: string
##         default: ""
##         description:
##             Add a suffix to a datacenter name. Used by the Ec2Snitch
##             and Ec2MultiRegionSnitch to append a string to the EC2
##             region name. Used with cassandra >= 1.2.x


    # Cassandra.yaml related options
    cluster_name:
        type: string
        default: "juju"
        description: >
            Name of the Cassandra cluster. This is mainly used to
            prevent machines in one logical cluster from joining
            another. All Cassandra services you wish to cluster together
            must have the same cluster_name. This setting cannot be changed
            after service deployment.
    partitioner:
        default: Murmur3Partitioner
        type: string
        description: >
            The cassandra partitioner to use. Use Murmur3Partitioner,
            unless another is required for backwards compatibility.
    num_tokens:
        type: int
        default: 256
        description: Number of tokens per node.
    force_seed_nodes:
        type: string
        default: ""
        description: >
            A comma separated list of seed node ip addresses. This is
            useful if the cluster being created in this juju environment
            is part of a larger cluser and the seed nodes are remote.
            
    # Topology of the service in the cluster.
    datacenter:
        type: string
        default: "juju"
        description: >
            The node's datacenter used by the endpoint_snitch. e.g. "DC1".
            It cannot be changed after service deployment.
    rack: 
        type: string
        default: ""
        description: >
            The rack used by the endpoint_snitch for all units in this
            service. e.g. "Rack1". This cannot be changed after deployment.
            It defaults to the service name. Cassandra will store replicated
            data in different racks whenever possible.
            
    # Networking options.
    cluster_port:
        type: int
        default: 7000
        description: Cluster communication port
    cluster_ssl_port:
        type: int
        default: 7001
        description: Cluster secure communication port
    thrift_client_port:
        type: int
        default: 9160
        description: Thrift protocol clients' port
    native_client_port:
        type: int
        default: 9042
        description: Native protocol clients' port
    jmx_port:
        type: int
        default: 7199
        description: JMX management port

    authorizer:
        type: string
        default: AllowAllAuthorizer
        description: >
            Authorization backend, implementing IAuthorizer; used to limit
            access/provide permissions Out of the box, Cassandra provides
            AllowAllAuthorizer & CassandraAuthorizer
            - AllowAllAuthorizer allows any action to any user - set it to
              disable authorization.
            - CassandraAuthorizer stores permissions in
              system_auth.permissions table.

    _post_bootstrap_wait:
        type: int
        default: 120
        description: >
            Testing option - do not change. When adding multiple new
            nodes to a cluster, you are supposed to wait two minutes
            between nodes. I set this to zero to speed up test runs.
              
    ##     compaction-throughput:
    ##         type: int
    ##         default: 16
    ##         description: >
    ##             Throttles compaction to the given total throughput (in MB/sec)
    ##             across the entire system. The faster you insert data, the faster
    ##             you need to compact in order to keep the sstable count down,
    ##             but in general, setting this to 16 to 32 times the rate you
    ##             are inserting data is more than sufficient.  Setting this to
    ##             0 disables throttling. Note that this account for all types
    ##             of compaction, including validation compaction.
    ##     stream-throughput:
    ##         type: int
    ##         default: 200
    ##         description: >
    ##            Throttles all outbound streaming file transfers on nodes to the
    ##            given total throughput in Mbps. This is necessary because Cassandra
    ##            does mostly sequential IO when streaming data during bootstrap or 
    ##            repair, which can lead to saturating the network connection and 
    ##            degrading rpc performance. When unset, the default is 200 Mbps or 25
    ##            MB/s. 0 to disable throttling.
    ##     commit_failure_policy: 
    ##         type: string
    ##         default: stop 
    ##         description: >
    ##              policy for commit disk failures. stop, stop_commit, ignore
    ##              stop: shut down gossip and Thrift, leaving the node effectively
    ##                    dead, but can still be inspected via JMX.
    ##              stop_commit: shutdown the commit log, letting writes collect but 
    ##                           continuing to service reads, as in pre-2.0.5
    ##                           Cassandra
    ##              ignore: ignore fatal errors and let the batches fail
    ##     tombstone_warn_threshold:
    ##         type: int
    ##         default: 1000
    ##         description: >
    ##             When executing a scan, within or across a partition, we
    ##             need to keep the tombstones seen in memory so we can return
    ##             them to the coordinator, which will use them to make sure
    ##             other replicas also know about the deleted rows. With
    ##             workloads that generate a lot of tombstones, this can cause
    ##             performance problems and even exaust the server heap. Adjust
    ##             the thresholds here if you understand the dangers and want
    ##             to scan more tombstones anyway.
    ##     tombstone_failure_threshold:
    ##         type: int
    ##         default: 100000
    ##         description: >
    ##             When executing a scan, within or across a partition, we need
    ##             to keep the tombstones seen in memory so we can return them
    ##             to the coordinator, which will use them to make sure other
    ##             replicas also know about the deleted rows. With workloads
    ##             that generate a lot of tombstones, this can cause
    ##             performance problems and even exaust the server heap. Adjust
    ##             the thresholds here if you understand the dangers and want
    ##             to scan more tombstones anyway.
    ##     batch_size_warn_threshold_in_kb:
    ##         type: int
    ##         default: 5
    ##         description:
    ##             Log WARN on any batch size exceeding this value. 5kb per batch by
    ##             default.
    ##     cas_contention_timeout_in_ms:
    ##         type: int
    ##         default: 1000
    ##         description: >
    ##             How long a coordinator should continue to retry a CAS operation
    ##             that contends with other proposals for the same row
    ##     preheat_kernel_page_cache:
    ##          type: string
    ##          default: "false"
    ##          description: >
    ##              Enable or disable kernel page cache preheating from
    ##              contents of the key cache after compaction.
    ## 
    ##     force-seed-nodes:
    ##         type: string
    ##         default: ""
    ##         description: >
    ##             A comma separated list of seed nodes. This is useful if the cluster
    ##             being created in this juju environment is part of a larger cluser
    ##             and the seed nodes are remote.
    ##     token-map-by-unitname:
    ##         type: string
    ##         default: ""
    ##         description: >
    ##             YAML map as e.g. "{ cassandra/0: 107950406921370402326527496543482482275, cassandra/1: 150485702786487710259449322472453508707 }".
    ##             Set initial_token according to the unit name using this map. Cannot be used  if token-map-by-volid is also set. If persistent storage
    ##             is being used then use token-map-by-volid instead.
    ##             Useful when rebalancing a ring by hand
    ##     token-map-by-volid:
    ##         type: string
    ##         default: ""
    ##         description: >
    ##             YAML map as e.g. "{ vol-00000012: 107950406921370402326527496543482482275, vol-00000013: 150485702786487710259449322472453508707 }".
    ##             Set initial_token according to the name of the attached volume using this map. Can only be used when using persistent storage
    ##             and cannot be used if token-map-by-unitname is also set. 
    ##             Useful when rebalancing a ring by hand
    ##     use-simpleauth:
    ##         type: boolean
    ##         default: false
    ##         description: |
    ##             If True, it will use passwd-prop64 and access-prop64 configs
    ##             (base64 encoded) to setup simple authentication by adding to JVM_OPTS:
    ##             -Dpasswd.properties=/etc/casssandra/passwd.properties \
    ##             -Daccess.properties=/etc/casssandra/access.properties
    ##             See http://www.datastax.com/docs/1.0/configuration/authentication
    ##     extra-jvm-opts:
    ##         type: string
    ##         default: ""
    ##         description: |
    ##             string to be appended to JVM_OPTS, e.g.:
    ##             -javaagent:$CASSANDRA_HOME/lib/jamm-0.2.5.jar
