#!/bin/sh -ex

TESTDIR=$(dirname $0)
CHARMDIR=$(dirname $TESTDIR)

# We need --system-site-packages for python3-apt.
virtualenv -p python3 --system-site-packages $TESTDIR/.venv

# Tests don't consistently run in a particular working directory.
# Create a symbolic link in the other potential working directory.
# This symbolic link must be relative to keep amulet and juju-deployer
# happy.
(cd $CHARMDIR && ln -sf tests/.venv .)

PIP=$TESTDIR/.venv/bin/pip3

$PIP install -q amulet
$PIP install -q cassandra-driver
$PIP install -q flake8
