#!/bin/bash

set -x

CWD=`dirname $0`

for node in `relation-list`
do
   HOSTNAME=`relation-get hostname ${node}`
   IP=`relation-get ip`
   DEFAULT_JMX_PORT=`relation-get jmx_port ${node}`
   DEFAULT_CLUSTER_PORT=`relation-get cluster_port ${node}`
   DEFAULT_CLIENT_PORT=`relation-get client_port ${node}`
   [ -z ${TMP_SEEDS} ] && TMP_SEEDS=${IP} || TMP_SEEDS="${TMP_SEEDS},${IP}"
done

sed -i -e "s/\- seeds:.*/\- seeds: \"${TMP_SEEDS}\"/" /etc/cassandra/cassandra.yaml

service cassandra status && service cassandra restart || service cassandra start

echo $ENSEMBLE_REMOTE_UNIT modified its settings
echo Relation settings:
relation-get
echo Relation members:
relation-list
