#!/bin/sh

set -x

HOSTNAME=`facter cassandra_hostname`
CWD=`dirname $0`
DEFAULT_JMX_PORT=`facter cassandra_default_jmx_port`
DEFAULT_CLUSTER_PORT=`facter cassandra_default_cluster_port`
DEFAULT_CLIENT_PORT=`facter cassandra_default_client_port`

relation-set hostname="${HOSTNAME}" jmx_port="${DEFAULT_JMX_PORT}" cluster_port="${DEFAULT_CLUSTER_PORT}" client_port="${DEFAULT_CLIENT_PORT}"
echo $ENSEMBLE_REMOTE_UNIT joined
