#!/bin/bash

set -ux

export LANG=en_US.UTF-8

# Install utility packages
DEBIAN_FRONTEND=noninteractive apt-get -y install python-software-properties

# Add facter and facter-plugins repository
echo deb http://ppa.launchpad.net/facter-plugins/ppa/ubuntu oneiric main  >> /etc/apt/sources.list.d/facter-plugins-ppa-oneiric.list
echo deb-src http://ppa.launchpad.net/facter-plugins/ppa/ubuntu oneiric main  >> /etc/apt/sources.list.d/facter-plugins-ppa-oneiric.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B696B50DD8914A9290A4923D6383E098F7D4BE4B

#apt-add-repository ppa:facter-plugins/ppa

# Install the repositories
echo "deb http://www.apache.org/dist/cassandra/debian unstable main" > /etc/apt/sources.list.d/cassandra.list
echo "deb-src http://www.apache.org/dist/cassandra/debian unstable main" >> /etc/apt/sources.list.d/cassandra.list

# Add the key
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F758CE318D77295D

# Update the repositories
apt-get update

# Install the package
DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-6-jre-headless jsvc libcommons-daemon-java adduser libjna-java facter facter-customfacts-plugin
cd /tmp
curl -O http://people.canonical.com/~negronjl/cassandra_0.8.3_all.deb
DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/cassandra_0.8.3_all.deb

HOSTNAME=`hostname -f`
CWD=`dirname $0`
DEFAULT_JMX_PORT=7199
DEFAULT_CLUSTER_PORT=7000
DEFAULT_CLIENT_PORT=9160

# Open the necessary ports
if [ -x /usr/bin/open-port ]; then
   open-port ${DEFAULT_JMX_PORT}/TCP
   open-port ${DEFAULT_CLUSTER_PORT}/TCP
   open-port ${DEFAULT_CLIENT_PORT}/TCP
fi

# Persist the data for future use
fact-add cassandra_hostname ${HOSTNAME}
fact-add cassandra_default_jmx_port ${DEFAULT_JMX_PORT}
fact-add cassandra_default_cluster_port ${DEFAULT_CLUSTER_PORT}
fact-add cassandra_default_client_port ${DEFAULT_CLIENT_PORT}

# Update the cassandra environment with the appropriate JMX port
mv /etc/cassandra/cassandra-env.sh /etc/cassandra/cassandra-env.sh.orig
sed -e s#__jmx_port__#${DEFAULT_JMX_PORT}# ${CWD}/../templats/cassandra_env_sh.tmpl > /etc/cassandra/cassandra-env.sh
chown root:root /etc/cassandra/cassandra-env.sh
chmod 644 /etc/cassandra/cassandra-env.sh

# Construct the cassandra.yaml file from the appropriate information above
mv /etc/cassandra/cassandra.yaml /etc/cassandra/cassandra.yaml.orig
cat ${CWD}/../templates/cassandra_yaml_top.tmpl > /etc/cassandra/cassandra.yaml
sed -e s#__hostname__#${HOSTNAME}# ${CWD}/../templates/cassandra_yaml_seeds.tmpl >> /etc/cassandra/cassandra.yaml
sed -e s#__cluster_port__#${DEFAULT_CLUSTER_PORT}# ${CWD}/../templates/cassandra_yaml_bottom.tmpl >> /etc/cassandra/cassandra.yaml
sed -e s#__hostname__#${HOSTNAME}# ${CWD}/../templates/cassandra_yaml_bottom.tmpl >> /etc/cassandra/cassandra.yaml
sed -e s#__client_port__#${DEFAULT_CLIENT_PORT}# ${CWD}/../templates/cassandra_yaml_bottom.tmpl >> /etc/cassandra/cassandra.yaml

chown root:root /etc/cassandra/cassandra.yaml
chmod 644 /etc/cassandra/cassandra.yaml

service cassandra status && service cassandra restart || service cassandra start
